name: Continuous Deployment VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: SSH into the VM and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VM_HOST }}
        username: ${{ secrets.VM_USERNAME }}
        password: ${{ secrets.VM_PASSWD }}
        script: |
          cd ~/tiebackend-runner/_work/StorePlay-backend/StorePlay-backend
          # Build and run the Docker image on the VM
          docker build -t store-backend .
          docker stop store-backend || true
          docker rm store-backend || true
          docker run -d --name store-backend -p 8081:8080 store-backend
